#!/bin/bash
# Simple banner generator for AGU

echo "========================================"
echo "        Welcome to banner4agu"
echo "========================================"
echo "This is a sample banner generated by bannercmd.sh"
echo "========================================"
